CC=gcc
CFLAGS= -ansi -Wall -pedantic

life2:
	gcc $(CFLAGS) -o life2.exe life2.c
lookup:
	gcc $(CFLAGS) -o lookup.exe lookup.c
lookups:
	gcc $(CFLAGS) -o lookups.exe lookups.c
revfile:
	gcc $(CFLAGS) -o revfile.exe revfile.c
clean:
	rm *.exe
