clean:
	rm *.exe

compound:
	gcc -ansi -g -pedantic -Wall -o compound.exe compound.c

longcompound:
	gcc -ansi -g -pedantic -Wall -o longcompound.exe longcompound.c

getbit:
	gcc -ansi -g -pedantic -Wall -o getbit.exe getbit.c
